# SPDX-License-Identifier: GPL-2.0+
#
# KaihongOS U-Boot BIOS (L2 common core)

ccflags-y += -I$(src)/include

obj-y += kh_bios.o
obj-y += kh_bios_board_weak.o
obj-y += kh_bios_hotkey.o
obj-y += kh_bios_ui.o
obj-y += kh_bios_ui_draw.o
obj-y += kh_bios_menu.o
obj-y += kh_bios_boot.o
obj-y += kh_bios_env.o
obj-y += kh_bios_security.o
obj-y += board/
